@startuml
!theme mars

actor Player as p
participant Game as g
participant Screen as s

p->g: press_key


alt Door on tile
    p->s: Show win screen
    s->p: Updated screen
    p->g: exit
else Enemy on tile
    g->p: Decrease health
    alt Health is 0
      p->s: Show loose screen
      s->p: Updated screen
      p->g: exit
    end
else Tile is empty
    g->g: Update player position
    g->s: Update screen
    s->p: Updated screen
else Wall on tile
    g->p: Position update declined
end

@enduml

