@startuml
!theme mars

left to right direction

actor User


(Press key) as pk


package Game {
  actor Enemy
  (Get damage) as gd
  (Quit the game) as qtg
  (Move to random position) as grp
  (Swap position with enemy) as swp
  (Update position) as up
    package Screen {
      (Redraw screen) as rds
      (Show message) as sm
      (Show loose message) as sbm
      (Show win message) as swm
    }
}


User -> gd
User -> pk
Enemy -> grp
Enemy -> swp

sbm .> sm
swm .> sm
sm .> gd


grp .> up
grp .> rds

pk .> up
pk .> rds
gd .> swp

qtg .> sm

@enduml
